services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    network_mode: "host"
    restart: unless-stopped

  bot:
    build:
      context: ./errbot
      dockerfile: Dockerfile
   
   
    env_file:
      - errbot/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    network_mode: "host"
    restart: unless-stopped
