sonar.projectKey=aleecar04_cano-bot
sonar.organization=aleecar04

sonar.sources=backend/app,errbot/plugins
sonar.tests=backend/tests,errbot/tests

sonar.python.version=3.11

sonar.exclusions=**/__pycache__/**,**/*.pyc,**/migrations/**,**/node_modules/**,cano-app/**

sonar.coverage.exclusions=backend/app/repositories/**,backend/app/core/db.py,backend/app/api/deps.py,backend/app/api/routes/login.py

sonar.python.coverage.reportPaths=backend-coverage.xml,bot-coverage.xml